spring.application.name=Grupo-Ginga-Capoeira
# Configurações do Servidor
server.port=8080

# Configurações do Banco de Dados (PostgreSQL)
# O Spring vai buscar os valores dentro dos ${} nas variáveis de ambiente do seu sistema ou IDE
spring.datasource.url=jdbc:postgresql://localhost:5432/db_grupoginga
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurações de Upload de Arquivos (Fotos dos Alunos)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Caminho para salvar as fotos (também via variável de ambiente para flexibilidade)
app.upload.dir=${APP_UPLOAD_PATH}